.TH RAMROOT 8 "2025-12-16" "ramroot 2.0.3" "ramroot manual"
.SH NAME
ramroot \- load root file system to zram during boot
.SH DESCRIPTION
\fBramroot\fR is a mkinitcpio hook that loads the root filesystem (and
optionally, other filesystems) to zram in early boot.  Ramroot checks for
available memory, and prompts users with the option to load the root filesystem

to zram before


.SH CONFIGURATION
\fBramroot\fR configuration is done via \fI/etc/ramroot.conf\fR.  A default configuration
only attempts to load the root \fI/\fR filesystem to zram.  The directories \fI/etc/ramroot.z/\fR and \fI~/ramroot.z/\fR may be used for additional customization.
.SH SEE ALSO
\fBramroot.conf\fR(5), <\fBhttps://github.com/arcmags/ramroot/\fR>
.SH COPYRIGHT
Copyright 2025 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3
or later <http://gnu.org/licenses/gpl.html>. This is free software: you are
free to change and redistribute it. There is NO WARRANTY, to the extent
permitted by law.
