#!/bin/bash
##========================  ramroot (build hook)  ========================##
# Place in: /usb/lib/initcpio/install/

build() {
    add_dir /local_part
    add_dir /zram_root
    add_module ext4
    add_module vfat
    add_module zram
    add_binary zramctl
    add_binary free
    add_binary mkfs.ext4
    add_binary nproc
    add_binary cp
    add_binary df
    add_file /etc/ramroot.conf /ramroot.conf
    add_runscript
}

help() {
    cat <<HELPEOF
This hook provides the option to load the root filesystem completely
into RAM during boot.
HELPEOF
}
