#!/bin/bash
## /usr/lib/initcpio/install/ramroot ::

build() {
    add_binary mkfs.ext4
    add_binary zramctl
    add_dir /local_root
    add_dir /zram_root
    add_file /etc/ramroot.conf
    add_module ext4
    add_module lz4
    add_module vfat
    add_module zram
    add_runscript
}

help() {
    cat <<HELPEOF
This hook optionally loads the root filesystem to zram during early userspace.
HELPEOF
}

# vim: ft=bash
