#!/bin/bash
##=====================  ramroot - initcpio install  =====================##
# Install script for ramroot initcpio hook.
# Place in: /usb/lib/initcpio/install

build() {
  add_dir /local_root
  add_dir /local_boot
  add_dir /zram_root
  add_binary zramctl
  add_binary free
  add_binary mkfs.ext4
  add_binary nproc
  add_runscript
}

help() {
  cat <<HELPEOF
This hook provides the option to load the root filesystem completely
into RAM during boot.
HELPEOF
}
